FROM --platform=linux/x86_64 redmine:5.0.0-bullseye

RUN apt update \
    && apt upgrade -y \
    && apt install -y \
        gcc \
        git \
        libmagic-dev \
        make \
        patch \
        postgresql-client \
        sudo \
        supervisor \
    && rm -rf /var/lib/apt/lists/* \
    && cd /usr/src/redmine \
    && git clone -b redmine4.2  https://github.com/farend/redmine_theme_farend_bleuclair.git public/themes/bleuclair

